SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1280

PLAYAREA_RADIUS = 640

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200  # pixels per second
PLAYER_BLINK_COOLDOWN = 2.0  # seconds
PLAYER_SPRINT_FACTOR = 2.0

PLAYER_MAX_STAMINA = 5.0  # seconds of sprinting
PLAYER_STAMINA_RECOVERY_RATE = 1.0  # seconds to recover 1 second of stamina

PLAYER_MAX_HEALTH = 100

EVENT_SPAWN_TIMER = 2.0  # seconds